name: Auto-close linked issues on PR merge

on:
  pull_request:
    types: [closed]

jobs:
  close_issues:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Auto-close referenced issues
        uses: actions/github-script@v6
        with:
          script: |
            const prBody = github.event.pull_request.body || "";
            const prNumber = github.event.pull_request.number;
            const issueNumbers = [...prBody.matchAll(/#(\d+)/g)].map(m => parseInt(m[1]));

            if (issueNumbers.length === 0) {
              console.log("No issue references found in PR body.");
              return;
            }

            for (const issueNumber of issueNumbers) {
              console.log(`Closing issue #${issueNumber}`);
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issueNumber,
                body: `Closed automatically via PR #${prNumber}.`
              });

              await github.rest.issues.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issueNumber,
                state: "closed"
              });
            }
